# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_points'),
        ('artworx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWorx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artname', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('totalpnts', models.IntegerField(default=100)),
                ('totalpntstyle', models.IntegerField(default=100)),
                ('totalpntsorig', models.IntegerField(default=100)),
                ('totalpntstech', models.IntegerField(default=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.User')),
                ('travellers', models.ManyToManyField(related_name='travellers', to='users.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='travellers',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
