# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworx', '0002_auto_20160728_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artworx',
            name='travellers',
        ),
    ]
